### ISSUE TITLE
Error creating backup repository RepositoryMissingException 

### ISSUE THREAD

**Issue by DrissiReda** [elastic/go-elasticsearch#181]
I'm trying to create a backup repository and saving snapshots on a opendistro es. My cluster is run on kubernetes and I have a single node.  The kubernetes deployment is throught his [helm](https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/)
My code:

```go
cfg := elasticsearch.Config{
		Addresses: endpoints,
		Username:  user,
		Password:  pass,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		},
		// ...
	}
	es, err := elasticsearch.NewClient(cfg)
        resp, err := es.Snapshot.CreateRepository("backup_minio", bytes.NewReader([]byte(`{"type":"fs","settings":{"location":"/usr/share/elasticsearch/data/backup"}}`))
```
I have that path added to `path.repo`.
The error I get is this:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[backup_minio] [[l4SUijXbS0KjJvWb_KJCrg, 'RemoteTransportException[[dev-opendistro-es-data-0][10.42.0.216:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[backup_minio] missing];']]"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[backup_minio] [[l4SUijXbS0KjJvWb_KJCrg, 'RemoteTransportException[[dev-opendistro-es-data-0][10.42.0.216:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[backup_minio] missing];']]"
  },
  "status": 500
}
```

Now we can see what's weird: 
There are files created under data/backup, so the problem isn't read/write rights.
And `/_snapshot/_all` gives this:
```json
{
  "backup_minio": {
    "type": "fs",
    "settings": {
      "location": "/usr/share/elasticsearch/data/backup"
    }
  }
}
```

If I attempt to create a snapshot. I have this returned:
```json
{
  "snapshots": [
    {
      "snapshot": "08182020-162700",
      "uuid": "zrRhVa1BTCqHyPOzWprIxA",
      "version_id": 7070099,
      "version": "7.7.0",
      "indices": [
        ".opendistro_security",
        "security-auditlog-2020.08.18",
        ".kibana_1"
      ],
      "include_global_state": true,
      "state": "PARTIAL",
      "start_time": "2020-08-18T14:27:00.434Z",
      "start_time_in_millis": 1597760820434,
      "end_time": "2020-08-18T14:27:02.041Z",
      "end_time_in_millis": 1597760822041,
      "duration_in_millis": 1607,
      "failures": [
        {
          "index": ".kibana_1",
          "index_uuid": ".kibana_1",
          "shard_id": 0,
          "reason": "RepositoryMissingException[[backup_minio] missing]
                         at org.elasticsearch.repositories.RepositoriesService.repository(RepositoriesService.java:378)
                         at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:339)
                         at org.elasticsearch.snapshots.SnapshotShardsService.lambda$startNewShards$1(SnapshotShardsService.java:289)
                         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633)
                         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                         at java.base/java.lang.Thread.run(Thread.java:835)",
          "node_id": "J5i8hlPpQF2_kFBelMkEkw",
          "status": "INTERNAL_SERVER_ERROR"
        },
        {
          "index": ".opendistro_security",
          "index_uuid": ".opendistro_security",
          "shard_id": 0,
          "reason": "RepositoryMissingException[[backup_minio] missing]
                         at org.elasticsearch.repositories.RepositoriesService.repository(RepositoriesService.java:378)
                         at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:339)
                         at org.elasticsearch.snapshots.SnapshotShardsService.lambda$startNewShards$1(SnapshotShardsService.java:289)
                         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633)
                         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                         at java.base/java.lang.Thread.run(Thread.java:835)",
          "node_id": "J5i8hlPpQF2_kFBelMkEkw",
          "status": "INTERNAL_SERVER_ERROR"
        },
        {
          "index": "security-auditlog-2020.08.18",
          "index_uuid": "security-auditlog-2020.08.18",
          "shard_id": 0,
          "reason": "RepositoryMissingException[[backup_minio] missing]
                         at org.elasticsearch.repositories.RepositoriesService.repository(RepositoriesService.java:378)
                         at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:339)
                         at org.elasticsearch.snapshots.SnapshotShardsService.lambda$startNewShards$1(SnapshotShardsService.java:289)
                         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633)
                         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                         at java.base/java.lang.Thread.run(Thread.java:835)",
          "node_id": "J5i8hlPpQF2_kFBelMkEkw",
          "status": "INTERNAL_SERVER_ERROR"
        }
      ],
      "shards": {
        "total": 3,
        "failed": 3,
        "successful": 0
      }
    }
  ]
}
```
And if I try to restore this backup, because I could see the files created. I get this:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
  },
  "status": 403
}
```
Does anyone have any idea where this is coming from?

**Comment by karmi** [comment]
Hello, this looks more related to Elasticsearch itself than the Go library. Maybe [enable logging](https://github.com/elastic/go-elasticsearch/tree/master/_examples/logging) in the client, so you can provide the requests and responses in the `curl` format, and ask at https://discuss.elastic.co?
