### ISSUE TITLE
v6 create index goroutine problem

### ISSUE THREAD

**Issue by lily-lee** [elastic/go-elasticsearch#63]
when the number of request growing, goroutine number keeps growing.

```
b, _ := json.Marshal(order)

resp, err := o.es.Index(
	order.GetCertainIndex(),
	bytes.NewReader(b),
	o.es.Index.WithDocumentID(order.ID),
	o.es.Index.WithDocumentType(order.GetType()),
	o.es.Index.WithRefresh("true"))
```

**Comment by karmi** [comment]
Hey, I'm afraid I need more information and context to understand the problem you're having...

**Comment by lily-lee** [comment]
I think the problem is caused by 

```
req, _ := newRequest(method, path.String(), nil)

func newRequest(method, path string, body io.Reader) (*http.Request, error) {
	r := http.Request{
		Method:     method,
		URL:        &url.URL{Path: path},
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		Header:     make(http.Header),
	}

	if body != nil {
		switch b := body.(type) {
		case *bytes.Buffer:
			r.Body = ioutil.NopCloser(body)
			r.ContentLength = int64(b.Len())
		case *bytes.Reader:
			r.Body = ioutil.NopCloser(body)
			r.ContentLength = int64(b.Len())
		case *strings.Reader:
			r.Body = ioutil.NopCloser(body)
			r.ContentLength = int64(b.Len())
		default:
			r.Body = ioutil.NopCloser(body)
		}
	}

	return &r, nil
}
```

when the request comes, Do func new a new http client. it cause the goroutine number growing when there are many request.

**Comment by lily-lee** [comment]
I use pprof to analyze the program, and I found that the http/transport is the main problem.

```
goroutine 706 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc001f6cfc0)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 1054 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc001d94900)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 778 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc00238ea20)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 1138 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc001b506c0)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 745 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc001f6d7a0)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 746 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc001f6d7a0)
	/usr/local/go/src/net/http/transport.go:1885 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1339 +0x966

goroutine 733 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc0022f6360)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 719 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc001fb3e60)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 838 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc00233b8c0)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

goroutine 705 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc0023687e0)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941

```

**Comment by karmi** [comment]
Thanks for the additional info. Can you post the code you're using with the client? There are subtleties when it comes to HTTP in Go, like closing the response body, draining it to make it use persistent connections, etc.

**Comment by lily-lee** [comment]
```
var err error
	once.Do(func() {
		Es, err = elasticsearch.NewClient(elasticsearch.Config{
			Addresses: config.Setting.ES.URLs,
			Transport: apmelasticsearch.WrapRoundTripper(&http.Transport{
				MaxIdleConns:        config.Setting.ES.MaxIdleConns,//10
				MaxIdleConnsPerHost: config.Setting.ES.MaxIdleConnsPerHost,//2
			}),
		})

		if err != nil {
			logrus.Panic("elastic.NewClient error: ", err)
		}
	})
```

**Comment by karmi** [comment]
... but this is just the client initializer, not executing any requests?

**Comment by lily-lee** [comment]
```
b, _ := json.Marshal(order)

resp, err := Es.Index(
	order.GetCertainIndex(),
	bytes.NewReader(b),
	Es.Index.WithDocumentID(order.ID),
	Es.Index.WithDocumentType(order.GetType()),
	Es.Index.WithRefresh("true"))
```
this one.

**Comment by karmi** [comment]
Right, then it figures — you're not closing the `resp.Body`, which triggers the errors you've posted in the backtrace.

So add something like: 

```golang
if resp.Body != nil {
  resp.Body.Close()
}
```

before the last line, `return nil`.

**Comment by lily-lee** [comment]
Thank you. Add the `resp.Body.Close()` and problem solved.

That's strange. 

In some case, we don't need to deal with the resp.

**Comment by karmi** [comment]
Glad to hear that!

And yes, the body needs to be closed even when you don't use it. It's specific to Go itself, not the client, but it's maybe a good thing to add to the documentation.
