### ISSUE TITLE
Assignment to entry in nil map when decoding JSON with typed API

### ISSUE THREAD

**Issue by ivancili** [elastic/go-elasticsearch#655]
Executing the code below using an Elastic search instance running in a docker container results in a panic. I was able to fix it by modifying the code downloaded locally using `go get`. I added `s.Properties = map[string]Property{}` after [this line](https://github.com/elastic/go-elasticsearch/blob/2691728e0254a53d63ad14d28b717ff6d9324f78/typedapi/types/typemapping.go#L124).

Docker command:
```bash
docker run --rm -p 9200:9200 -p 9300:9300 \
        -e "discovery.type=single-node" \
        -e "xpack.security.enabled=false" \
        -e "ingest.geoip.downloader.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:8.6.2
```

Go example code:
```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/elastic/go-elasticsearch/v8/typedapi/indices/create"
	"github.com/elastic/go-elasticsearch/v8/typedapi/types"
)

func main() {
	client, err := elasticsearch.NewTypedClient(elasticsearch.Config{
		Addresses: []string{"http://localhost:9200"},
	})
	if err != nil {
		log.Fatal(err)
	}

	metric := "l2_norm"
	indexTrue := true

	createResponse, err := client.Indices.Create("my-index").Request(&create.Request{
		Settings: &types.IndexSettings{NumberOfReplicas: "1", NumberOfShards: "2"},
		Mappings: &types.TypeMapping{
			Properties: map[string]types.Property{
				"embedding": types.DenseVectorProperty{
					Dims:       1,
					Similarity: &metric,
					Index:      &indexTrue,
					Type:       "dense_vector",
				},
			},
		},
	}).Do(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	getMappingResponse, err := client.Indices.GetMapping().Index("_all").Do(context.Background())
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(getMappingResponse)
}
```
Output
```bash
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/elastic/go-elasticsearch/v8/typedapi/types.(*TypeMapping).UnmarshalJSON(0x140000ce008, {0x140000b6018, 0x61, 0x1e8})
	/Users/ivancili/go/pkg/mod/github.com/elastic/go-elasticsearch/v8@v8.7.0/typedapi/types/typemapping.go:236 +0x34a4
encoding/json.(*decodeState).object(0x140000b4028, {0x1032f5480?, 0x140000ce008?, 0x103217160?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/decode.go:613 +0x650
encoding/json.(*decodeState).value(0x140000b4028, {0x1032f5480?, 0x140000ce008?, 0x8?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/decode.go:374 +0x40
encoding/json.(*decodeState).object(0x140000b4028, {0x10326a180?, 0x140000ce000?, 0x102d989f0?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/decode.go:775 +0xb34
encoding/json.(*decodeState).value(0x140000b4028, {0x10326a180?, 0x140000ce000?, 0x102e82900?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/decode.go:374 +0x40
encoding/json.(*decodeState).object(0x140000b4028, {0x1031fb0e0?, 0x1400000fda8?, 0x102da7f5c?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/decode.go:775 +0xb34
encoding/json.(*decodeState).value(0x140000b4028, {0x1031fb0e0?, 0x1400000fda8?, 0x102da7c10?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/decode.go:374 +0x40
encoding/json.(*decodeState).unmarshal(0x140000b4028, {0x1031fb0e0?, 0x1400000fda8?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/decode.go:181 +0x184
encoding/json.(*Decoder).Decode(0x140000b4000, {0x1031fb0e0, 0x1400000fda8})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/encoding/json/stream.go:73 +0x130
github.com/elastic/go-elasticsearch/v8/typedapi/indices/getmapping.GetMapping.Do({{0x10330d2e8, 0x140000261e0}, 0x140001df800, 0x140001df7d0, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...}, ...)
	/Users/ivancili/go/pkg/mod/github.com/elastic/go-elasticsearch/v8@v8.7.0/typedapi/indices/getmapping/get_mapping.go:169 +0x14c
main.main()
	/Users/ivancili/Desktop/x.go:42 +0x3ec
exit status 2

```

**Comment by alexartwww** [comment]
Same behavior for FormJSON method.

**Comment by alexartwww** [comment]
Then I've got panic: could not deserialise json into Create request: json: cannot unmarshal string into Go struct field Request.mappings of type bool

looks like typedclient is very unstable

**Comment by ivancili** [comment]
looks like it, switching to the untyped client
